"""
Stages 2 & 4: LLM-as-judge evaluation.

Two separate judges are used: one scores the ticket summary (factual accuracy,
completeness, conciseness, actionability, tone), and a second scores the
generated customer email (policy alignment, instruction-following, grounding,
tone, actionability) -- including a scope check that catches cases where a
ticket isn't actually related to the company at all.
"""

from langchain_openai import ChatOpenAI

from .config import MODEL_NAME
from .policies import SUPPORT_POLICIES, COMPANY_NAME
from .utils import safe_parse_json, strip_code_fences

_llm = ChatOpenAI(
    model_name=MODEL_NAME,
    temperature=0.2,
    max_tokens=350,
)

SUMMARY_EVAL_SYSTEM_MESSAGE = """You are an impartial LLM-as-judge evaluating the quality of a generated customer support ticket summary.

Your task is to evaluate whether the summary accurately captures the customer issue, preserves the key details, and is useful for a support agent.
Focus on factual accuracy, completeness, conciseness, actionability, tone, and clarity.

Return valid JSON only with these fields:
{
  "factual_accuracy": 1-5,
  "completeness": 1-5,
  "conciseness": 1-5,
  "actionability": 1-5,
  "tone_and_clarity": 1-5,
  "overall_score": 1-5,
  "justification": "Brief explanation"
}

Do not include any extra text outside the JSON object.
"""

RESPONSE_EVALUATION_SYSTEM_MESSAGE = f"""You are an impartial evaluator reviewing customer support email responses generated by an LLM for {COMPANY_NAME}.

Your task is to evaluate whether the generated email response is appropriate, accurate, policy-aligned, and customer-facing.

Evaluate the response using only the information provided in the original ticket, ticket summary, internal evaluation, response-generation instructions, and {COMPANY_NAME} policies. Do not assume facts that are not provided.

Evaluation criteria:

0. Scope Check
- Determine whether the original ticket is actually related to {COMPANY_NAME}, a {COMPANY_NAME} order, or a {COMPANY_NAME} policy.
- If the ticket is about another company, delivery service, platform, or unrelated issue, a standard {COMPANY_NAME} support response should not be generated.
- For out-of-scope tickets, an appropriate response should politely explain that the issue does not appear to be related to {COMPANY_NAME} and recommend contacting the correct provider.
- If the generated email treats an out-of-scope ticket as a {COMPANY_NAME} issue, this is a critical failure.

1. Policy Alignment
- Does the response follow the relevant {COMPANY_NAME} policy or policies?
- Does it avoid making promises, refunds, replacements, cancellations, or delivery guarantees that are not supported by policy?

2. Instruction Following
- Does the response follow the response-generation instructions?
- Does it avoid mentioning internal labels, scores, evaluations, confidence levels, or model analysis?
- Does it include a clear subject line and customer-facing email format?

3. Accuracy and Grounding
- Is the response grounded in the ticket details?
- Does it avoid inventing order details, customer names, timelines, policy terms, or resolutions?

4. Tone and Professionalism
- Is the response empathetic, professional, concise, and helpful?

5. Actionability
- Does the response provide a clear next step, resolution path, or explanation?

Return your evaluation in valid JSON only using this exact schema:
{{
  "scope_check": {{"should_generate_standard_response": true or false, "score": 1-5, "justification": "Brief explanation"}},
  "policy_alignment": {{"score": 1-5, "justification": "Brief explanation"}},
  "instruction_following": {{"score": 1-5, "justification": "Brief explanation"}},
  "accuracy_and_grounding": {{"score": 1-5, "justification": "Brief explanation"}},
  "tone_and_professionalism": {{"score": 1-5, "justification": "Brief explanation"}},
  "actionability": {{"score": 1-5, "justification": "Brief explanation"}},
  "overall_score": 1-5,
  "passed": true or false,
  "critical_issues": ["List any major issues, or an empty list if none"],
  "recommendation": "approve, revise, or reject"
}}

Set passed to false and recommendation to reject if the original ticket is not
related to {COMPANY_NAME} and the generated response treats it as a {COMPANY_NAME} issue,
or if the response invents unsupported facts, exposes internal evaluation details,
or contradicts policy.

Return JSON only. Do not include markdown, commentary, or rewritten email text.
"""


def generate_summary_evaluation(ticket_text: str, summary_text: str) -> dict:
    """Generate a structured evaluation for one support ticket summary."""
    user_message = f"""Evaluate the quality of the generated summary for the support ticket below.
Support Ticket:
{ticket_text}
Summary:
{summary_text}
"""
    response = _llm.invoke([
        ("system", SUMMARY_EVAL_SYSTEM_MESSAGE),
        ("human", user_message),
    ])

    parsed = safe_parse_json(strip_code_fences(response.content.strip()))
    if parsed is not None:
        return parsed

    return {
        "factual_accuracy": 1, "completeness": 1, "conciseness": 1,
        "actionability": 1, "tone_and_clarity": 1, "overall_score": 1,
        "justification": "evaluation parse failed",
    }


def evaluate_email_response(ticket_text: str, ticket_summary: dict,
                             ticket_evaluation: dict, email_response: str,
                             email_response_system_message: str) -> dict:
    """Generate a structured LLM-as-judge evaluation for one email response."""
    user_message = f"""
Evaluate the generated customer email response below.

Original Ticket:
{ticket_text}

Ticket Summary:
{ticket_summary}

Internal Evaluation:
{ticket_evaluation}

Response Generation Instructions and {COMPANY_NAME} Policies:
{email_response_system_message}

Generated Email Response:
{email_response}
"""
    response = _llm.invoke([
        ("system", RESPONSE_EVALUATION_SYSTEM_MESSAGE),
        ("human", user_message),
    ])

    parsed = safe_parse_json(strip_code_fences(response.content.strip()))
    if parsed is not None:
        return parsed

    return {
        "scope_check": {"should_generate_standard_response": True, "score": 1, "justification": "evaluation parse failed"},
        "policy_alignment": {"score": 1, "justification": "evaluation parse failed"},
        "instruction_following": {"score": 1, "justification": "evaluation parse failed"},
        "accuracy_and_grounding": {"score": 1, "justification": "evaluation parse failed"},
        "tone_and_professionalism": {"score": 1, "justification": "evaluation parse failed"},
        "actionability": {"score": 1, "justification": "evaluation parse failed"},
        "overall_score": 1,
        "passed": False,
        "critical_issues": ["evaluation_failed"],
        "recommendation": "reject",
    }
